// flow-typed signature: 09849d367366f1529f257864bafab449
// flow-typed version: <<STUB>>/react-shadow-wrapper_v^1.0.6/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-shadow-wrapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-shadow-wrapper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-shadow-wrapper/index' {
  declare module.exports: $Exports<'react-shadow-wrapper'>;
}
declare module 'react-shadow-wrapper/index.js' {
  declare module.exports: $Exports<'react-shadow-wrapper'>;
}
